// internal/proto/revealr.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: internal/proto/revealr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages for Go to Python communication
type ScanResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Host          *Host                  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	ScanConfig    *ScanConfig            `protobuf:"bytes,3,opt,name=scan_config,json=scanConfig,proto3" json:"scan_config,omitempty"` // NEW: Add scan_config to ScanResultRequest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResultRequest) Reset() {
	*x = ScanResultRequest{}
	mi := &file_internal_proto_revealr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResultRequest) ProtoMessage() {}

func (x *ScanResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_revealr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResultRequest.ProtoReflect.Descriptor instead.
func (*ScanResultRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_revealr_proto_rawDescGZIP(), []int{0}
}

func (x *ScanResultRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ScanResultRequest) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *ScanResultRequest) GetScanConfig() *ScanConfig {
	if x != nil {
		return x.ScanConfig
	}
	return nil
}

type ScanResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResultResponse) Reset() {
	*x = ScanResultResponse{}
	mi := &file_internal_proto_revealr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResultResponse) ProtoMessage() {}

func (x *ScanResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_revealr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResultResponse.ProtoReflect.Descriptor instead.
func (*ScanResultResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_revealr_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScanResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Messages for Python to Go communication (updates)
type PortDetailUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScanId         string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	HostId         string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	PortNumber     int32                  `protobuf:"varint,3,opt,name=port_number,json=portNumber,proto3" json:"port_number,omitempty"`
	Protocol       string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ServiceName    string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceVersion string                 `protobuf:"bytes,6,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	Details        map[string]string      `protobuf:"bytes,7,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PortDetailUpdate) Reset() {
	*x = PortDetailUpdate{}
	mi := &file_internal_proto_revealr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortDetailUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortDetailUpdate) ProtoMessage() {}

func (x *PortDetailUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_revealr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortDetailUpdate.ProtoReflect.Descriptor instead.
func (*PortDetailUpdate) Descriptor() ([]byte, []int) {
	return file_internal_proto_revealr_proto_rawDescGZIP(), []int{2}
}

func (x *PortDetailUpdate) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *PortDetailUpdate) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *PortDetailUpdate) GetPortNumber() int32 {
	if x != nil {
		return x.PortNumber
	}
	return 0
}

func (x *PortDetailUpdate) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PortDetailUpdate) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PortDetailUpdate) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *PortDetailUpdate) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_internal_proto_revealr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_revealr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_revealr_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// NEW: Message to carry scan configuration details to Python
type ScanConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanTiming    string                 `protobuf:"bytes,1,opt,name=scan_timing,json=scanTiming,proto3" json:"scan_timing,omitempty"` // e.g., "default", "fast", "aggressive", "slow", "insane"
	Debug         bool                   `protobuf:"varint,2,opt,name=debug,proto3" json:"debug,omitempty"`                            // Pass debug mode to Python
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanConfig) Reset() {
	*x = ScanConfig{}
	mi := &file_internal_proto_revealr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanConfig) ProtoMessage() {}

func (x *ScanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_revealr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanConfig.ProtoReflect.Descriptor instead.
func (*ScanConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_revealr_proto_rawDescGZIP(), []int{4}
}

func (x *ScanConfig) GetScanTiming() string {
	if x != nil {
		return x.ScanTiming
	}
	return ""
}

func (x *ScanConfig) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

// Core Data Structures (mirroring Go's core/types.go for protobuf)
type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	IsUp          bool                   `protobuf:"varint,3,opt,name=is_up,json=isUp,proto3" json:"is_up,omitempty"`
	Ports         []*Port                `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_internal_proto_revealr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_revealr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_internal_proto_revealr_proto_rawDescGZIP(), []int{5}
}

func (x *Host) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Host) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Host) GetIsUp() bool {
	if x != nil {
		return x.IsUp
	}
	return false
}

func (x *Host) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Host) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortNumber    int32                  `protobuf:"varint,1,opt,name=port_number,json=portNumber,proto3" json:"port_number,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	IsOpen        bool                   `protobuf:"varint,3,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	Service       *Service               `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_internal_proto_revealr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_revealr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_internal_proto_revealr_proto_rawDescGZIP(), []int{6}
}

func (x *Port) GetPortNumber() int32 {
	if x != nil {
		return x.PortNumber
	}
	return 0
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Port) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *Port) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Port) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_internal_proto_revealr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_revealr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_internal_proto_revealr_proto_rawDescGZIP(), []int{7}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Service) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_internal_proto_revealr_proto protoreflect.FileDescriptor

const file_internal_proto_revealr_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/revealr.proto\x12\rrevealr_proto\"\x91\x01\n" +
	"\x11ScanResultRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12'\n" +
	"\x04host\x18\x02 \x01(\v2\x13.revealr_proto.HostR\x04host\x12:\n" +
	"\vscan_config\x18\x03 \x01(\v2\x19.revealr_proto.ScanConfigR\n" +
	"scanConfig\"H\n" +
	"\x12ScanResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd1\x02\n" +
	"\x10PortDetailUpdate\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1f\n" +
	"\vport_number\x18\x03 \x01(\x05R\n" +
	"portNumber\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x06 \x01(\tR\x0eserviceVersion\x12F\n" +
	"\adetails\x18\a \x03(\v2,.revealr_proto.PortDetailUpdate.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\n" +
	"ScanConfig\x12\x1f\n" +
	"\vscan_timing\x18\x01 \x01(\tR\n" +
	"scanTiming\x12\x14\n" +
	"\x05debug\x18\x02 \x01(\bR\x05debug\"\xed\x01\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x13\n" +
	"\x05is_up\x18\x03 \x01(\bR\x04isUp\x12)\n" +
	"\x05ports\x18\x04 \x03(\v2\x13.revealr_proto.PortR\x05ports\x12:\n" +
	"\adetails\x18\x05 \x03(\v2 .revealr_proto.Host.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x02\n" +
	"\x04Port\x12\x1f\n" +
	"\vport_number\x18\x01 \x01(\x05R\n" +
	"portNumber\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x17\n" +
	"\ais_open\x18\x03 \x01(\bR\x06isOpen\x120\n" +
	"\aservice\x18\x04 \x01(\v2\x16.revealr_proto.ServiceR\aservice\x12:\n" +
	"\adetails\x18\x05 \x03(\v2 .revealr_proto.Port.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12=\n" +
	"\adetails\x18\x03 \x03(\v2#.revealr_proto.Service.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012i\n" +
	"\rPythonService\x12X\n" +
	"\x11ProcessScanResult\x12 .revealr_proto.ScanResultRequest\x1a!.revealr_proto.ScanResultResponse2_\n" +
	"\tGoService\x12R\n" +
	"\x10UpdatePortDetail\x12\x1f.revealr_proto.PortDetailUpdate\x1a\x1d.revealr_proto.UpdateResponseB\x18Z\x16revealr/internal/protob\x06proto3"

var (
	file_internal_proto_revealr_proto_rawDescOnce sync.Once
	file_internal_proto_revealr_proto_rawDescData []byte
)

func file_internal_proto_revealr_proto_rawDescGZIP() []byte {
	file_internal_proto_revealr_proto_rawDescOnce.Do(func() {
		file_internal_proto_revealr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_revealr_proto_rawDesc), len(file_internal_proto_revealr_proto_rawDesc)))
	})
	return file_internal_proto_revealr_proto_rawDescData
}

var file_internal_proto_revealr_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_proto_revealr_proto_goTypes = []any{
	(*ScanResultRequest)(nil),  // 0: revealr_proto.ScanResultRequest
	(*ScanResultResponse)(nil), // 1: revealr_proto.ScanResultResponse
	(*PortDetailUpdate)(nil),   // 2: revealr_proto.PortDetailUpdate
	(*UpdateResponse)(nil),     // 3: revealr_proto.UpdateResponse
	(*ScanConfig)(nil),         // 4: revealr_proto.ScanConfig
	(*Host)(nil),               // 5: revealr_proto.Host
	(*Port)(nil),               // 6: revealr_proto.Port
	(*Service)(nil),            // 7: revealr_proto.Service
	nil,                        // 8: revealr_proto.PortDetailUpdate.DetailsEntry
	nil,                        // 9: revealr_proto.Host.DetailsEntry
	nil,                        // 10: revealr_proto.Port.DetailsEntry
	nil,                        // 11: revealr_proto.Service.DetailsEntry
}
var file_internal_proto_revealr_proto_depIdxs = []int32{
	5,  // 0: revealr_proto.ScanResultRequest.host:type_name -> revealr_proto.Host
	4,  // 1: revealr_proto.ScanResultRequest.scan_config:type_name -> revealr_proto.ScanConfig
	8,  // 2: revealr_proto.PortDetailUpdate.details:type_name -> revealr_proto.PortDetailUpdate.DetailsEntry
	6,  // 3: revealr_proto.Host.ports:type_name -> revealr_proto.Port
	9,  // 4: revealr_proto.Host.details:type_name -> revealr_proto.Host.DetailsEntry
	7,  // 5: revealr_proto.Port.service:type_name -> revealr_proto.Service
	10, // 6: revealr_proto.Port.details:type_name -> revealr_proto.Port.DetailsEntry
	11, // 7: revealr_proto.Service.details:type_name -> revealr_proto.Service.DetailsEntry
	0,  // 8: revealr_proto.PythonService.ProcessScanResult:input_type -> revealr_proto.ScanResultRequest
	2,  // 9: revealr_proto.GoService.UpdatePortDetail:input_type -> revealr_proto.PortDetailUpdate
	1,  // 10: revealr_proto.PythonService.ProcessScanResult:output_type -> revealr_proto.ScanResultResponse
	3,  // 11: revealr_proto.GoService.UpdatePortDetail:output_type -> revealr_proto.UpdateResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_proto_revealr_proto_init() }
func file_internal_proto_revealr_proto_init() {
	if File_internal_proto_revealr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_revealr_proto_rawDesc), len(file_internal_proto_revealr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_proto_revealr_proto_goTypes,
		DependencyIndexes: file_internal_proto_revealr_proto_depIdxs,
		MessageInfos:      file_internal_proto_revealr_proto_msgTypes,
	}.Build()
	File_internal_proto_revealr_proto = out.File
	file_internal_proto_revealr_proto_goTypes = nil
	file_internal_proto_revealr_proto_depIdxs = nil
}
