// internal/proto/revealr.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc1
// source: internal/proto/revealr.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PythonService_ProcessScanResult_FullMethodName = "/revealr_proto.PythonService/ProcessScanResult"
)

// PythonServiceClient is the client API for PythonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition: Go (client) sends data to Python (server)
type PythonServiceClient interface {
	ProcessScanResult(ctx context.Context, in *ScanResultRequest, opts ...grpc.CallOption) (*ScanResultResponse, error)
}

type pythonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPythonServiceClient(cc grpc.ClientConnInterface) PythonServiceClient {
	return &pythonServiceClient{cc}
}

func (c *pythonServiceClient) ProcessScanResult(ctx context.Context, in *ScanResultRequest, opts ...grpc.CallOption) (*ScanResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResultResponse)
	err := c.cc.Invoke(ctx, PythonService_ProcessScanResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PythonServiceServer is the server API for PythonService service.
// All implementations must embed UnimplementedPythonServiceServer
// for forward compatibility.
//
// Service definition: Go (client) sends data to Python (server)
type PythonServiceServer interface {
	ProcessScanResult(context.Context, *ScanResultRequest) (*ScanResultResponse, error)
	mustEmbedUnimplementedPythonServiceServer()
}

// UnimplementedPythonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPythonServiceServer struct{}

func (UnimplementedPythonServiceServer) ProcessScanResult(context.Context, *ScanResultRequest) (*ScanResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessScanResult not implemented")
}
func (UnimplementedPythonServiceServer) mustEmbedUnimplementedPythonServiceServer() {}
func (UnimplementedPythonServiceServer) testEmbeddedByValue()                       {}

// UnsafePythonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PythonServiceServer will
// result in compilation errors.
type UnsafePythonServiceServer interface {
	mustEmbedUnimplementedPythonServiceServer()
}

func RegisterPythonServiceServer(s grpc.ServiceRegistrar, srv PythonServiceServer) {
	// If the following call pancis, it indicates UnimplementedPythonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PythonService_ServiceDesc, srv)
}

func _PythonService_ProcessScanResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PythonServiceServer).ProcessScanResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PythonService_ProcessScanResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PythonServiceServer).ProcessScanResult(ctx, req.(*ScanResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PythonService_ServiceDesc is the grpc.ServiceDesc for PythonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PythonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revealr_proto.PythonService",
	HandlerType: (*PythonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessScanResult",
			Handler:    _PythonService_ProcessScanResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/revealr.proto",
}

const (
	GoService_UpdatePortDetail_FullMethodName = "/revealr_proto.GoService/UpdatePortDetail"
)

// GoServiceClient is the client API for GoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition: Python (client) sends updates back to Go (server)
type GoServiceClient interface {
	UpdatePortDetail(ctx context.Context, in *PortDetailUpdate, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type goServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoServiceClient(cc grpc.ClientConnInterface) GoServiceClient {
	return &goServiceClient{cc}
}

func (c *goServiceClient) UpdatePortDetail(ctx context.Context, in *PortDetailUpdate, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, GoService_UpdatePortDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoServiceServer is the server API for GoService service.
// All implementations must embed UnimplementedGoServiceServer
// for forward compatibility.
//
// Service definition: Python (client) sends updates back to Go (server)
type GoServiceServer interface {
	UpdatePortDetail(context.Context, *PortDetailUpdate) (*UpdateResponse, error)
	mustEmbedUnimplementedGoServiceServer()
}

// UnimplementedGoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoServiceServer struct{}

func (UnimplementedGoServiceServer) UpdatePortDetail(context.Context, *PortDetailUpdate) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePortDetail not implemented")
}
func (UnimplementedGoServiceServer) mustEmbedUnimplementedGoServiceServer() {}
func (UnimplementedGoServiceServer) testEmbeddedByValue()                   {}

// UnsafeGoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoServiceServer will
// result in compilation errors.
type UnsafeGoServiceServer interface {
	mustEmbedUnimplementedGoServiceServer()
}

func RegisterGoServiceServer(s grpc.ServiceRegistrar, srv GoServiceServer) {
	// If the following call pancis, it indicates UnimplementedGoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoService_ServiceDesc, srv)
}

func _GoService_UpdatePortDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortDetailUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoServiceServer).UpdatePortDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoService_UpdatePortDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoServiceServer).UpdatePortDetail(ctx, req.(*PortDetailUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// GoService_ServiceDesc is the grpc.ServiceDesc for GoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "revealr_proto.GoService",
	HandlerType: (*GoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePortDetail",
			Handler:    _GoService_UpdatePortDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/revealr.proto",
}
