# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import revealr_pb2 as revealr__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in revealr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PythonServiceStub(object):
    """Service definition: Go (client) sends data to Python (server)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessScanResult = channel.unary_unary(
                '/revealr_proto.PythonService/ProcessScanResult',
                request_serializer=revealr__pb2.ScanResultRequest.SerializeToString,
                response_deserializer=revealr__pb2.ScanResultResponse.FromString,
                _registered_method=True)


class PythonServiceServicer(object):
    """Service definition: Go (client) sends data to Python (server)
    """

    def ProcessScanResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessScanResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessScanResult,
                    request_deserializer=revealr__pb2.ScanResultRequest.FromString,
                    response_serializer=revealr__pb2.ScanResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'revealr_proto.PythonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('revealr_proto.PythonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonService(object):
    """Service definition: Go (client) sends data to Python (server)
    """

    @staticmethod
    def ProcessScanResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/revealr_proto.PythonService/ProcessScanResult',
            revealr__pb2.ScanResultRequest.SerializeToString,
            revealr__pb2.ScanResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GoServiceStub(object):
    """Service definition: Python (client) sends updates back to Go (server)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdatePortDetail = channel.unary_unary(
                '/revealr_proto.GoService/UpdatePortDetail',
                request_serializer=revealr__pb2.PortDetailUpdate.SerializeToString,
                response_deserializer=revealr__pb2.UpdateResponse.FromString,
                _registered_method=True)


class GoServiceServicer(object):
    """Service definition: Python (client) sends updates back to Go (server)
    """

    def UpdatePortDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdatePortDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePortDetail,
                    request_deserializer=revealr__pb2.PortDetailUpdate.FromString,
                    response_serializer=revealr__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'revealr_proto.GoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('revealr_proto.GoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GoService(object):
    """Service definition: Python (client) sends updates back to Go (server)
    """

    @staticmethod
    def UpdatePortDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/revealr_proto.GoService/UpdatePortDetail',
            revealr__pb2.PortDetailUpdate.SerializeToString,
            revealr__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
